In [1]:
import numpy as np
from IPython.display import display, Markdown, Latex
from array_to_latex import to_ltx
from herramientas.tools import random_state, vector2latex, unitary2latex2

In [2]:
latex_formatter = get_ipython().display_formatter.formatters["text/latex"]
latex_formatter.for_type(np.ndarray, lambda m: to_ltx(m, print_out=False))

In [4]:
A= np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
j=0+1j
B=A+A*j
B

array([[1.+1.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+1.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+1.j]])

In [5]:
from array_to_latex import to_ltx
to_markdown = lambda m: f"$$\n{to_ltx(m, print_out=False)}\n$$"
print(to_markdown(A))

$$
\begin{bmatrix}
  1.00 &  0.00 &  0.00\\
  0.00 &  1.00 &  0.00\\
  0.00 &  0.00 &  1.00
\end{bmatrix}
$$


$$
\begin{bmatrix}
  1.00 &  0.00 &  0.00\\
  0.00 &  1.00 &  0.00\\
  0.00 &  0.00 &  1.00
\end{bmatrix}
$$


In [6]:
a=np.array([1+2j,0+1j])

In [7]:
a

array([1.+2.j, 0.+1.j])

In [8]:
M_fin=vector2latex(a, pretext="|\\psi\\rangle =")

/media/alejogq/DATA/QISKIT_ALEJO/INVESTIGACION/HERRAMIENTAS DE DISPLAY/herramientas/tools.py:11: ComplexWarning: Casting complex values to real discards the imaginary part
  out_latex += str(int(np.round(amplitude))) + " \\\\\n"



$$ |\psi\rangle =\begin{bmatrix}
1 \\
0\end{bmatrix} $$

In [9]:
M_fin=unitary2latex2(B, pretext="|\\psi\\rangle =")

/media/alejogq/DATA/QISKIT_ALEJO/INVESTIGACION/HERRAMIENTAS DE DISPLAY/herramientas/tools.py:50: ComplexWarning: Casting complex values to real discards the imaginary part
  out_latex += str(int(np.round(amplitude))) +"+" +"("+str(np.round(np.imag(amplitude),1))+" j "+")"+" & "



$$ |\psi\rangle =\begin{bmatrix}
	1+(1.0 j ) & 0+(0.0 j ) & 0+(0.0 j )  \\
	0+(0.0 j ) & 1+(1.0 j ) & 0+(0.0 j )  \\
	0+(0.0 j ) & 0+(0.0 j ) & 1+(1.0 j )  \\
\end{bmatrix} $$

To print a result from state vector simulation use the following in your code:m

In [19]:
## To print a result from state vector simulation use teh following in your code:

#ket = job.result().get_statevector()
#for amplitude in ket:
#    print(amplitude)